[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.228"
serde_json = "1.0.149"
tokio = "1.49.0"
pbrsdk = { path = ".." }

[dev-dependencies]
once_cell = "1.21.3"
